---

enable_hardware: false

servo_base: &servo_base
  low: 50
  high: 1000
  init: 0.5
  invert: false

led_base: &led_base
  low: 0
  high: 1000
  init: 0.2

pwm_channels:
  head_pan:
    <<: *servo_base
    channel: 2
    invert: true
    low: 200
    high: 500

  head_tilt:
    <<: *servo_base
    channel: 4
    low: 400
    high: 500
    init: 0.3

  left_arm:
    <<: *servo_base
    channel: 1
    low: 200
    high: 500
    init: 0

  right_arm:
    <<: *servo_base
    channel: 0
    invert: true
    low: 300
    high: 550
    init: 0

  torso:
    <<: *servo_base
    channel: 3
    low: 200
    high: 500

  left_eye_r:
    <<: *led_base
    channel: 12

  left_eye_g:
    <<: *led_base
    channel: 13

  left_eye_b:
    <<: *led_base
    channel: 14

  right_eye_r:
    <<: *led_base
    channel: 8

  right_eye_g:
    <<: *led_base
    channel: 9

  right_eye_b:
    <<: *led_base
    channel: 10

led_display:
  - clock_pin: 20
    data_pin: 21
    segments: 16

  - clock_pin: 19
    data_pin: 26
    segments: 16

# font from https://fontstruct.com/fontstructions/show/325977/4x3_pixel
letters:
  " ": [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]
  0: [ false, true, true, false, true, true, false, true, false, true, true, false, false, false, false, false,  ]
  1: [ false, false, false, true, true, true, true, true, true, false, false, true, false, false, false, false,  ]
  2: [ false, true, false, true, true, false, true, true, true, false, false, true, false, false, false, false,  ]
  3: [ false, true, true, false, true, true, false, true, true, false, false, true, false, false, false, false,  ]
  4: [ true, true, true, true, false, true, false, false, true, true, false, false, false, false, false, false,  ]
  5: [ true, false, true, false, true, true, false, true, true, true, false, false, false, false, false, false,  ]
  6: [ true, false, true, false, true, false, true, true, false, true, true, true, false, false, false, false,  ]
  7: [ true, true, false, false, true, false, true, false, true, false, false, true, false, false, false, false,  ]
  8: [ true, true, true, true, true, true, false, true, true, true, true, true, false, false, false, false,  ]
  9: [ true, true, true, false, true, true, false, true, false, true, false, true, false, false, false, false,  ]
  .: [ false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false,  ]
  A: [ false, true, true, true, true, false, true, false, false, true, true, true, false, false, false, false ]
  B: [ true, false, true, false, true, true, false, true, true, true, true, true, false, false, false, false ]
  C: [ true, false, false, true, true, false, false, true, false, true, true, false, false, false, false, false ]
  D: [ false, true, true, false, true, false, false, true, true, true, true, true, false, false, false, false ]
  E: [ true, false, false, true, true, true, false, true, true, true, true, true, false, false, false, false ]
  F: [ true, false, false, false, true, true, false, false, true, true, true, true, false, false, false, false ]
  G: [ true, false, true, true, true, false, false, true, false, true, true, false, false, false, false, false ]
  H: [ true, true, true, true, false, true, false, false, true, true, true, true, false, false, false, false,  ]
  I: [ true, false, false, true, true, true, true, true, true, false, false, true, false, false, false, false,  ]
  J: [ true, true, true, false, true, false, false, true, true, false, true, false, false, false, false, false,  ]
  K: [ true, false, true, true, false, true, false, false, true, true, true, true, false, false, false, false,  ]
  L: [ false, false, false, true, false, false, false, true, true, true, true, true, false, false, false, false,  ]
  M: [ true, true, true, true, true, true, false, false, true, true, true, true, false, false, false, false,  ]
  N: [ false, true, true, true, true, false, false, false, true, true, true, true, false, false, false, false,  ]
  O: [ false, true, true, false, true, false, false, true, false, true, true, false, false, false, false, false,  ]
  P: [ true, true, true, false, true, false, true, false, true, true, true, true, false, false, false, false,  ]
  Q: [ false, true, true, true, true, false, true, true, false, true, true, false, false, false, false, false,  ]
  R: [ false, true, false, true, true, false, true, false, true, true, true, true, false, false, false, false,  ]
  S: [ true, false, true, true, true, true, false, true, true, true, false, true, false, false, false, false,  ]
  T: [ true, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false,  ]
  U: [ true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false,  ]
  V: [ true, true, false, false, false, false, true, false, true, true, true, true, false, false, false, false,  ]
  W: [ true, true, true, true, false, false, true, true, true, true, true, true, false, false, false, false,  ]
  X: [ true, false, true, true, false, true, false, false, true, false, true, true, false, false, false, false,  ]
  Y: [ true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false,  ]
  Z: [ true, false, false, true, true, true, false, true, true, false, true, true, false, false, false, false,  ]
